# Generated by Django 4.2.1 on 2023-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_submenu_is_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='is_menu',
            field=models.BooleanField(default=True),
        ),
    ]
