# Generated by Django 4.2.1 on 2023-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_submenu_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_mainBanner',
            field=models.BooleanField(default=True),
        ),
    ]
