# Generated by Django 4.2.1 on 2023-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_menu_is_mainbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_mainBanner',
            field=models.BooleanField(default=False),
        ),
    ]
