# Generated by Django 4.2.1 on 2023-07-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_mainbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
