# Generated by Django 4.2.1 on 2023-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_addcategoryitem_category_remove_mainbanner_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_short_desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
