# Generated by Django 4.2.1 on 2023-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_category_category_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcategoryitem',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
