# Generated by Django 4.2.1 on 2023-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_addcategoryitem_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='html_page',
            field=models.CharField(default=1, help_text="Enter the HTML page name without extension (e.g., 'about' for 'about.html')", max_length=100),
            preserve_default=False,
        ),
    ]
