# Generated by Django 4.2.1 on 2023-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_mainbanner_html_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='html_page',
            field=models.CharField(blank=True, default=False, help_text="Enter the HTML page name without extension (e.g., 'about' for 'about.html')", max_length=100),
        ),
    ]
