# Generated by Django 4.2.1 on 2023-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_menu_html_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='html_page',
            field=models.CharField(help_text="Enter the HTML page name without extension (e.g.,'/about' for 'about.html')", max_length=100),
        ),
    ]
