# Generated by Django 4.2.1 on 2023-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_category_is_active_alter_mainbanner_html_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('paragraph_one', models.TextField()),
                ('paragraph_two', models.TextField()),
                ('paragraph_three', models.TextField()),
                ('quote', models.TextField()),
            ],
        ),
    ]
