# Generated by Django 4.2.1 on 2023-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_explore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_product_title', models.CharField(max_length=100)),
                ('first_product_subtitle', models.CharField(max_length=100)),
                ('first_product_image', models.ImageField(upload_to='explore-products/')),
                ('second_product_title', models.CharField(max_length=100)),
                ('second_product_subtitle', models.CharField(max_length=100)),
                ('second_product_image', models.ImageField(upload_to='explore-products/')),
            ],
        ),
    ]
