# Generated by Django 4.2.1 on 2023-07-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_socialmediaitem_socialmediasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
