# Generated by Django 4.2.1 on 2023-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_aboutusteamsection_twitter_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusteamsection',
            name='behance_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutusteamsection',
            name='facebook_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutusteamsection',
            name='instagram_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutusteamsection',
            name='linkedin_link',
            field=models.CharField(max_length=150),
        ),
    ]
