# Generated by Django 4.2.1 on 2023-07-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_aboutusteamsection_behance_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusteamsection',
            old_name='instagram_link',
            new_name='twitter_link',
        ),
    ]
